dist: trusty
sudo: required

language: python
python: "3.6"

before_install:
    - sudo pip3 install cython==0.24
    - sudo pip3 install kivy==1.10.0
    - sudo pip3 install kivymd
    - sudo pip3 install buildozer


script:
    - buildozer android debug
