dist: trusty
sudo: required

language: python
version: "3.6"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install build-essential ccache git lib32z1 lib32bz2-1.0 libncurses5:i386 libstdc++6:i386 python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386
    - sudo apt-get install build-essential git libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
    - sudo pip install --upgrade cython
    - sudo pip install --upgrade kivy
    - sudo pip install --upgrade kivymd
    - sudo pip install --upgrade buildozer


script:
    - buildozer android debug
